"""
Generate mixed-precision GGUF files using llama-quantize.

Takes a knapsack allocation and produces a single GGUF with
per-layer quantization levels.
"""

import os
import subprocess
import tempfile


class GGUFGenerator:
    """
    Generate mixed-precision GGUF files.

    Uses llama-quantize's --tensor-type flag to apply different
    quantization levels to different layers.
    """

    # Mapping from our quant names to llama.cpp tensor-type strings
    QUANT_MAP = {
        "BF16":  "bf16",
        "Q8_0":  "q8_0",
        "Q6_K":  "q6_k",
        "Q5_K":  "q5_k",
        "Q4_K":  "q4_k",
        "Q4_0":  "q4_0",
        "Q3_K":  "q3_k",
        "Q2_K":  "q2_k",
        "IQ2_M": "iq2_m",
    }

    # Tensor name patterns for each transformer layer
    LAYER_TENSORS = [
        "attn_q.weight",
        "attn_k.weight",
        "attn_v.weight",
        "attn_output.weight",
        "ffn_gate.weight",
        "ffn_up.weight",
        "ffn_down.weight",
    ]

    def __init__(self, llama_quantize="llama-quantize"):
        self.llama_quantize = llama_quantize

    def generate(self, source_model, allocation, output_path):
        """
        Generate a mixed-precision GGUF file.

        Args:
            source_model: Path to BF16/F16 source GGUF
            allocation: Result from KnapsackSolver.solve()
            output_path: Where to write the output GGUF
        """
        if not os.path.exists(source_model):
            raise FileNotFoundError(f"Source model not found: {source_model}")

        # Determine the most common quantization level (used as the base)
        level_dist = allocation["level_distribution"]
        base_quant = max(level_dist, key=level_dist.get)
        base_quant_str = self.QUANT_MAP[base_quant]

        print(f"\n   🔧 Generating adaptive GGUF")
        print(f"   Base quantization: {base_quant} ({level_dist[base_quant]}/{len(allocation['layers'])} layers)")
        print(f"   Source: {source_model}")
        print(f"   Output: {output_path}")

        # Build the llama-quantize command
        cmd = [
            self.llama_quantize,
            source_model,
            output_path,
            base_quant_str,
        ]

        # Add per-tensor type overrides for layers that differ from base
        override_count = 0
        for layer in allocation["layers"]:
            if layer["quant"] != base_quant:
                quant_str = self.QUANT_MAP[layer["quant"]]
                layer_idx = layer["index"]

                for tensor_name in self.LAYER_TENSORS:
                    cmd.extend([
                        "--tensor-type",
                        f"blk.{layer_idx}.{tensor_name}={quant_str}"
                    ])
                override_count += 1

        print(f"   Overrides: {override_count} layers differ from base")
        print(f"   Running llama-quantize...")

        # Execute
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=3600,
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"llama-quantize failed (exit {result.returncode}):\n"
                f"STDOUT: {result.stdout[-500:]}\n"
                f"STDERR: {result.stderr[-500:]}"
            )

        # Verify output
        if os.path.exists(output_path):
            size_gb = os.path.getsize(output_path) / (1024 ** 3)
            print(f"   Output size: {size_gb:.2f}GB")
            print(f"   Compression: {allocation.get('compression_ratio', 0):.1f}x from BF16")
        else:
            raise RuntimeError(f"Output file not created: {output_path}")

    def generate_script(self, source_model, allocation, output_path="adaptive.gguf"):
        """
        Generate a shell script that can be run later.

        Useful when you want to profile on one machine and quantize on another.
        """
        level_dist = allocation["level_distribution"]
        base_quant = max(level_dist, key=level_dist.get)
        base_quant_str = self.QUANT_MAP[base_quant]

        lines = [
            "#!/bin/bash",
            "# Generated by adaptive-quant",
            f"# Model: {source_model}",
            f"# Budget: {allocation['budget_gb']}GB",
            f"# Avg bits: {allocation['avg_bits_per_weight']}",
            f"# Compression: {allocation.get('compression_ratio', 0):.1f}x",
            "",
            f"llama-quantize \\",
            f"  {source_model} \\",
            f"  {output_path} \\",
            f"  {base_quant_str} \\",
        ]

        for layer in allocation["layers"]:
            if layer["quant"] != base_quant:
                quant_str = self.QUANT_MAP[layer["quant"]]
                layer_idx = layer["index"]
                for tensor_name in self.LAYER_TENSORS:
                    lines.append(f"  --tensor-type blk.{layer_idx}.{tensor_name}={quant_str} \\")

        # Remove trailing backslash from last line
        lines[-1] = lines[-1].rstrip(" \\")

        return "\n".join(lines)
